pipeline {
  agent {
    docker {
      image 'node:6-alpine'
      args '-p 3000:3000'
    }
  }
  stages {
    stage('Build') {
      steps {
        sh 'npm install'
      }
    }
    stage('Deliver') {
      steps {
        sh 'chmod -R +x ./jenkins/scripts/'
        sh './jenkins/scripts/deliver.sh'
      }
    }
  }
}